name: team_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/852_Logo.png
    - assets/852_Logo_Blue.png

fonts:
  - family: Spectral
    fonts:
      - asset: assets/Spectral-ExtraBoldItalic.ttf
      - asset: assets/Spectral-Light.ttf
      - asset: assets/Spectral-MediumItalic.ttf
        weight: 800
